spring:
  jpa:
    show-sql: true
  application:
    name: bookshop
  datasource:
    url: jdbc:mysql://localhost:3306/bookshop
    username: root
    password: admin
#    driver-class-name: com.mysql.cj.jdbc.Driver

#logging:
#  level:
#    com.coursework.bookshop: debug
#    org.springframework.web: error
#  pattern:
#    console: "%d{MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
#    file: "%d{YYYY-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
#  file:
#    name: genericshop.log
#    append: false
#    max-size: 1MB
#    max-history: 5



server:
  port: 8085


eureka:
  client:
    enabled: true

app:
  api:
    path:
      version:
        v1: "api/v1"
      book:
        createBook: "/book/create"
        deleteBook: "/book/delete"
        deleteBooks: "/book/deleteByAuthor"
        updateBook: "/book/update"
        getBooks: "/books"
        getBook: "/book"
      author:
        createAuthor: "/author/create"
        getAuthors: "/authors"
        getAuthorNames: "/author/names"
        getAuthor: "/author"
        updateAuthor: "/author/update"
        deleteAuthor: "/author/delete"
      user:
        getUser: "/user"
        createUser: "/user/create"

