spring:
  jpa:
    show-sql: true
  application:
    name: bookshop
  datasource:
    url: jdbc:mysql://localhost:3306/bookshop
    username: root
    password: admin
#    driver-class-name: com.mysql.cj.jdbc.Driver


server:
  port: 8085

app:
  api:
    path:
      version:
        v1: "api/v1"
      book:
        createBook: "/book"
        deleteBook: "/book/delete"
        getBook: "/book"
      author:
        createAuthor: "/author/create"


